import type { ReactNode } from 'react';
import styled from 'styled-components';
import { Icon, type Appearance } from '../Appearance';
import { Button } from './components';
const Shell = styled('div')({ display: 'grid', gridTemplateColumns: '88px minmax(0, 1fr)', minHeight: '100dvh', '@media(max-width: 700px)': { gridTemplateColumns: '64px minmax(0, 1fr)' } });
const Nav = styled('nav')({ position: 'sticky', top: 0, height: '100dvh', padding: '24px 8px', background: '#163d36', color: '#e4eee7', display: 'flex', flexDirection: 'column', gap: 10, alignItems: 'center', '& > svg': { width: 32, height: 32, marginBottom: 0 }, '& button': { flexDirection: 'column', width: '100%', padding: '12px 2px', fontSize: 11, fontWeight: 500, background: 'transparent', color: '#e4eee7', border: 0 }, '& button[aria-pressed=true]': { background: '#2d554b', color: '#ffffff' }, '& button:focus-visible': { outlineColor: '#c4e4d2' }, '& button:not(:disabled):hover': { background: '#2d554b', filter: 'none' }, '@media(max-width: 700px)': { padding: '20px 4px' } });
const Main = styled('main')({ minWidth: 0, padding: '24px 28px', '@media(max-width: 1100px)': { padding: '20px' }, '@media(max-width: 700px)': { padding: '16px 12px' } });
interface Props { children: ReactNode; appearance: Appearance; toggleTheme: () => void; repositories: () => void; settings: () => void; disabled: boolean; incoming?: () => void; outgoing?: () => void; direction?: 'incoming' | 'outgoing' }
export function AppShell({ children, appearance, toggleTheme, repositories, settings, disabled, incoming, outgoing, direction }: Props): React.JSX.Element {
  return <Shell><Nav aria-label="Основная навигация"><Icon name="sync" /><strong style={{ fontSize: 11, marginBottom: 20 }}>RepoSync</strong><Button aria-label="Репозитории" disabled={disabled} onClick={repositories}><Icon name="folder" />Проекты</Button>{incoming && <Button aria-pressed={direction === 'incoming'} disabled={disabled} onClick={incoming}><Icon name="import" />Получение</Button>}{outgoing && <Button aria-pressed={direction === 'outgoing'} disabled={disabled} onClick={outgoing}><Icon name="arrow" />Отправка</Button>}<Button style={{ marginTop: 'auto' }} aria-label="Сменить тему" onClick={toggleTheme}><Icon name={appearance === 'dark' ? 'sun' : 'moon'} />Тема</Button><Button aria-label="Настройки приложения" disabled={disabled} onClick={settings}><Icon name="settings" />Настройки</Button></Nav><Main>{children}</Main></Shell>;
}
