import { useState } from 'react';
import type { BranchContext, CommitOption, IncomingSelection } from '../../shared/types';
import { Button, Muted, Row, Surface } from '../ui/components';

export function IncomingSource({ branch, context, selection, commits, busy, change, compare, reload }: { branch: string; context: BranchContext; selection: IncomingSelection; commits: CommitOption[]; busy: boolean; change: (selection: IncomingSelection) => void; compare: (selection: IncomingSelection) => void; reload: () => void }): React.JSX.Element {
  const [query, setQuery] = useState(''); const [editingBase, setEditingBase] = useState(false);
  const { mode, baseBranch, from } = selection;
  const selected = selection.commit || commits[0]?.sha || '';
  const choices = commits.filter(item => item.sha === selected || item.sha === from || `${item.sha} ${item.subject ?? ''} ${item.date}`.toLowerCase().includes(query.toLowerCase()));
  const items = choices.map(item => <option key={item.sha} value={item.sha}>{item.date} · {item.sha.slice(0, 10)} · {item.subject ?? ''}</option>);
  return <Surface style={{ marginBottom: 12, padding: '12px 16px' }}><Row style={{ justifyContent: 'space-between' }}><strong>Ветка: {selection.branch ?? branch}{mode === 'branch' && ` · Основа: ${baseBranch || 'не выбрана'}`}</strong><Button disabled={busy} onClick={reload}>Обновить источник</Button></Row>
    <details open={mode !== 'branch' || !baseBranch || baseBranch === (selection.branch ?? branch)}><summary>Другой способ / настройка ветки</summary><fieldset disabled={busy} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16, marginTop: 16 }}>
      <label>Внешняя ветка<select value={selection.branch ?? branch} onChange={event => change({ mode, branch: event.target.value, baseBranch })}>{context.branches.map(name => <option key={name}>{name}</option>)}</select></label>
      <label>Способ сравнения<select value={mode} onChange={event => change({ mode: event.target.value as IncomingSelection['mode'], branch: selection.branch ?? branch, baseBranch })}><option value="branch">Изменения ветки</option><option value="commit">По коммиту</option><option value="range">Между двумя коммитами</option><option value="repositories">Сравнить репозитории целиком</option><option value="zero">От нулевого состояния</option></select></label>
      {mode === 'branch' && <div style={{ gridColumn: '1 / -1' }}><Row><strong>Изменения {selection.branch ?? branch} относительно {baseBranch || 'невыбранной основы'}</strong><Button onClick={() => setEditingBase(value => !value)}>Сменить основу</Button></Row>{(!baseBranch || editingBase) && <label style={{ marginTop: 12 }}>Основная ветка<select value={baseBranch ?? ''} onChange={event => { change({ ...selection, baseBranch: event.target.value || undefined }); setEditingBase(false); }}><option value="">Выберите основу</option>{[...context.branches].sort((a, b) => Number(['main', 'master', 'develop'].includes(b)) - Number(['main', 'master', 'develop'].includes(a))).map(name => <option key={name}>{name}</option>)}</select></label>}<Muted style={{ marginBottom: 0 }}>{baseBranch === (selection.branch ?? branch) ? 'Выбрана сама основная ветка. Смените внешнюю ветку или способ сравнения.' : 'Берём изменения от общего предка до вершины выбранной ветки. Новые коммиты основы не переносятся обратно.'}</Muted></div>}
      {(mode === 'commit' || mode === 'range') && <><input aria-label="Поиск коммита" placeholder="Найти по SHA, названию или дате…" value={query} onChange={event => setQuery(event.target.value)} />{mode === 'range' && <label>Исходное состояние A<select value={from ?? ''} onChange={event => change({ ...selection, from: event.target.value || undefined })}><option value="">Выберите начальный коммит</option>{items}</select></label>}<label>{mode === 'commit' ? 'Коммит' : 'Конечное состояние B'}<select value={selected} onChange={event => change({ ...selection, commit: event.target.value })}>{!commits.length && <option value="">История не загружена</option>}{items}</select></label><small>{mode === 'commit' ? 'Изменения коммита относительно первого родителя.' : 'Точный diff A → B независимо от родства и порядка коммитов.'}</small></>}
      {mode === 'repositories' && <small>Полное сравнение локальной и внешней веток, включая удаления локальных файлов, отсутствующих снаружи.</small>}
      {mode === 'zero' && <small>Внешние файлы добавляются; отличающиеся существующие файлы вызовут конфликт.</small>}
    </fieldset><Row style={{ justifyContent: 'flex-end', marginTop: 16 }}><Button $primary disabled={busy || (mode === 'branch' && (!baseBranch || baseBranch === (selection.branch ?? branch))) || ((mode === 'commit' || mode === 'range') && !selected) || (mode === 'range' && !from)} onClick={() => compare({ ...selection, ...(mode === 'commit' || mode === 'range' ? { commit: selected } : {}) })}>Показать изменения</Button></Row>
  </details></Surface>;
}
