import { useState } from 'react';
import type { Analysis, Finding } from '../../shared/types';
import { Badge, Button, EmptyState, Muted, Row, Surface } from '../ui/components';
export function SecurityReview({ analysis, kept, keep, exclude, replace, open, busy }: { analysis: Analysis; kept: string[]; keep: (id: string) => void; exclude: (finding: Finding) => void; replace: (finding: Finding) => void; open: (finding: Finding) => void; busy: boolean }): React.JSX.Element {
  const [selected, setSelected] = useState('');
  const findings = analysis.findings;
  const finding = findings.find(item => item.id === selected && !kept.includes(item.id)) ?? findings.find(item => !kept.includes(item.id));
  if (!finding) return <EmptyState title="Проверка данных завершена"><Muted>{findings.length ? 'Все найденные совпадения рассмотрены.' : 'Совпадений с правилами проверки не найдено.'}</Muted><small>Автоматическая проверка может пропустить чувствительные данные. Просмотрите изменения перед синхронизацией.</small></EmptyState>;
  const index = findings.indexOf(finding);
  return <Surface style={{ maxWidth: 850, margin: '32px auto' }}><Row style={{ justifyContent: 'space-between' }}><h2 style={{ margin: 0 }}>Проверка данных</h2><Badge>Рассмотрено: {kept.length} / {findings.length}</Badge></Row><Muted>{index + 1} / {findings.length} · {finding.severity === 'block' ? 'Возможные данные доступа' : 'Возможные персональные данные'}</Muted><h3>{finding.reason}</h3><Muted>Значения скрыты только в просмотре. «Оставить в пакете» сохраняет исходные данные. Исключение файла сохраняется в настройках.</Muted><code>{finding.path} · строка {finding.line}</code><pre style={{ padding: 24, margin: '24px 0', background: 'var(--input)', borderRadius: 8, whiteSpace: 'pre-wrap', lineHeight: 1.7 }}><code>{finding.context ? <>{finding.context.before}<mark style={{ color: 'var(--warning)', background: 'var(--raised)' }}>{finding.context.match}</mark>{finding.context.after}</> : finding.preview}</code></pre><small>{finding.context?.location}</small><Row style={{ marginTop: 24 }}><Button disabled={busy} onClick={() => exclude(finding)}>Исключить файл</Button>{finding.canReplace && <Button disabled={busy} onClick={() => replace(finding)}>Заменить в исходнике</Button>}<Button $primary disabled={busy} onClick={() => keep(finding.id)}>Оставить в пакете</Button><Button disabled={busy} onClick={() => open(finding)}>Показать файл</Button></Row><Row style={{ marginTop: 24 }}><Button disabled={busy || index === 0} onClick={() => setSelected(findings[index - 1]!.id)}>Предыдущее</Button><Button disabled={busy || index === findings.length - 1} onClick={() => setSelected(findings[index + 1]!.id)}>Следующее</Button></Row></Surface>;
}
