import type { Analysis, CodeComparison, Direction, Finding, ImportPreview, Profile, Settings } from '../../shared/types';
import { Icon } from '../Appearance';
import { Comparison } from '../Comparison';
import { SecurityReview } from './SecurityReview';
import { Button, EmptyState, Muted, Row, Status, StepIndicator, Surface } from '../ui/components';
export type SyncStep = 'source' | 'compare' | 'security' | 'package' | 'apply' | 'done';
interface Props {
  profile: Profile; settings: Settings; direction: Direction; step: SyncStep;
  analysis: Analysis | null; importPreview: ImportPreview | null; comparison: CodeComparison | null;
  kept: string[]; override: boolean; exported: string[]; busy: boolean; locked: boolean;
  error: string; retryComparison: () => void;
  pending: React.MutableRefObject<Promise<void> | null>; setPreviewBusy: (busy: boolean) => void;
  setStep: (step: SyncStep) => void; setOverride: (override: boolean) => void;
  close: () => void; keep: (ids: string[], retained: boolean) => void; exclude: (finding: Finding) => void;
  replace: (finding: Finding) => void; showFinding: (finding: Finding) => void;
  completeReview: () => void; chooseOutput: () => void; exportPackage: () => void;
  apply: () => void; openRepository: () => void;
  selectedIncomingPaths: string[]; onSelectedIncomingPathsChange: (paths: string[]) => void;
}
export function SyncWorkflow({ profile, settings, direction, step, analysis, importPreview, comparison, kept, override, exported, busy, locked, error, retryComparison, pending, setPreviewBusy, setStep, setOverride, close, keep, exclude, replace, showFinding, completeReview, chooseOutput, exportPackage, apply, openRepository, selectedIncomingPaths, onSelectedIncomingPathsChange }: Props): React.JSX.Element {
  const remainingPaths = new Set(importPreview?.entries.map(entry => entry.path));
  const working = analysis?.workingChanges ?? importPreview?.workingChanges;
  const steps = direction === 'outgoing' ? ['Сравнение', 'Проверка данных', 'Пакет', 'Готово'] : profile.role === 'external' ? ['Пакет', 'Просмотр', 'Применение', 'Готово'] : ['Изменения', 'Применение', 'Готово'];
  const current = step === 'done' ? steps.length - 1 : direction === 'outgoing' ? step === 'compare' ? 0 : step === 'security' ? 1 : 2 : profile.role === 'external' ? step === 'compare' ? 1 : step === 'apply' ? 2 : 0 : step === 'source' || step === 'compare' ? 0 : 1;
  const undecided = analysis?.findings.filter(finding => !kept.includes(finding.id)).length ?? 0;
  return <>
        <Row style={{ justifyContent: 'space-between' }}><h2 style={{ margin: 0 }}>{direction === 'outgoing' ? 'Подготовка пакета изменений' : 'Входящие изменения'}</h2><Button disabled={locked} onClick={close}>{step === 'done' ? 'К репозиторию' : 'Закрыть'}</Button></Row>
        <StepIndicator steps={steps} current={current} />
        {direction === 'incoming' && analysis && (analysis.incomingMode === 'branch' || analysis.incomingMode === 'commit' || analysis.incomingMode === 'range') && <small>Добавлений: {analysis.changes.ADD} · Изменений: {analysis.changes.MODIFY + analysis.changes.REPLACE} · Удалений: {analysis.changes.DELETE} · Переименований: {analysis.changes.RENAME}. Остальные локальные файлы сохраняются.</small>}
        {analysis?.incomingMode === 'repositories' && <Status>Полное сравнение: локальная ветка → внешняя ветка. Совпадающие файлы не показаны. Файлы, которые есть только в локальной ветке, отмечены для удаления — проверьте их перед применением.</Status>}
        {analysis?.incomingMode === 'zero' && <Status>От нулевого состояния: все выбранные внешние файлы добавляются. Отличающиеся внутренние файлы не будут перезаписаны.</Status>}
        {analysis?.branchComparison && <details style={{ margin: '12px 0' }}><summary>Границы сравнения ветки</summary><small>Ветка: {analysis.branchComparison.branch} · Основа: {analysis.branchComparison.baseBranch} · Вершина основы: <code>{analysis.branchComparison.baseHead}</code></small></details>}
        {analysis?.packageType === 'snapshot' && direction === 'outgoing' && <Status>Первый пакет содержит выбранные файлы ветки. Общее состояние сохраняется только при полном переносе.</Status>}
        {working && working.staged + working.unstaged + working.untracked > 0 && <Status>{direction === 'incoming' ? 'Незакоммиченные изменения не входят в исходный diff. Выбранные изменяемые файлы заменяются целиком; правки вне выбранных путей сохраняются.' : 'Изменения без коммита не входят в пакет.'} В индексе — {working.staged}, вне индекса — {working.unstaged}, новых файлов — {working.untracked}.</Status>}
        {(step === 'compare' || step === 'apply') && comparison && <Comparison comparison={comparison} busy={busy} onBusy={setPreviewBusy} request={pending} selectable alreadyAppliedPaths={importPreview ? selectedIncomingPaths.filter(path => !remainingPaths.has(path)) : []} selectedPaths={selectedIncomingPaths} onSelectedPathsChange={onSelectedIncomingPathsChange} />}
        {error && <Status $error role="alert">{error}{direction === 'incoming' && (step === 'compare' || step === 'apply') && <p><Button disabled={locked} onClick={retryComparison}>{profile.role === 'external' ? 'Выбрать пакет заново' : 'Обновить сравнение'}</Button></p>}</Status>}
        {busy && direction === 'incoming' && step === 'compare' && <Status role="status">Проверка применения… Дождитесь результата.</Status>}
        {(step === 'compare' || step === 'apply') && comparison && <Row style={{ position: 'sticky', bottom: 0, zIndex: 2, padding: '16px 20px', marginTop: 16, background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: 12, justifyContent: 'space-between' }}><div><strong>Выбрано: {selectedIncomingPaths.length} из {comparison.entries.length}</strong><small style={{ display: 'block' }}>{comparison.entries.length === 0 ? 'Новых изменений нет.' : selectedIncomingPaths.length === 0 ? 'Выберите хотя бы один файл или папку.' : selectedIncomingPaths.length < comparison.entries.length ? 'Частичный перенос не обновляет общее состояние синхронизации.' : 'Будут обработаны выбранные операции.'}</small></div><Button $primary disabled={locked || !!error || (comparison.entries.length > 0 && selectedIncomingPaths.length === 0) || (direction === 'outgoing' && comparison.entries.length === 0)} onClick={step === 'apply' ? apply : completeReview}>{step === 'apply' ? importPreview?.entries.length ? `Применить изменения · ${importPreview.entries.length}` : 'Подтвердить результат' : direction === 'incoming' ? 'Проверить применение' : 'Проверить данные'} <Icon name="arrow" /></Button></Row>}

        {direction === 'outgoing' && step === 'security' && analysis && <><SecurityReview analysis={analysis} kept={kept} keep={keep} exclude={exclude} replace={replace} open={showFinding} busy={locked} />{direction === 'outgoing' && analysis.findings.some(finding => finding.severity === 'block') && <label style={{ display: 'flex', alignItems: 'center', margin: '16px 0', gap: 10 }}><input type="checkbox" disabled={locked} checked={override} onChange={e => setOverride(e.target.checked)} />Разрешаю включить в пакет оставшиеся возможные пароли, токены и ключи.</label>}<Row style={{ justifyContent: 'space-between', marginTop: 20 }}><Button disabled={locked} onClick={() => setStep('compare')}>К сравнению</Button><Row>{undecided > 0 && <small>Осталось проверить: {undecided}</small>}<Button $primary disabled={locked || undecided > 0 || (direction === 'outgoing' && analysis.findings.some(finding => finding.severity === 'block') && !override)} onClick={completeReview}>{direction === 'outgoing' ? 'Перейти к пакету' : 'Проверить применение'}</Button></Row></Row></>}
        {step === 'package' && analysis && <Surface><h2>Создание пакета</h2><Muted>Файлов: {selectedIncomingPaths.length} · Частей .md: {analysis.parts} · {(analysis.estimatedBytes / 1024).toLocaleString('ru-RU', { minimumFractionDigits: 1, maximumFractionDigits: 1 })} КБ · {profile.transportMode === 'compact' ? 'Компактный' : 'Читаемый'}</Muted><p><code>{settings.outputDirectory || 'Папка для пакетов не выбрана'}</code></p><Row><Button disabled={locked} onClick={chooseOutput}>Выбрать папку</Button><Button $primary disabled={locked || !settings.outputDirectory} onClick={exportPackage}>Создать пакет</Button></Row><small style={{ display: 'block', marginTop: 20 }}>Все части нужно передать вместе, сохранив имена. После подтверждения полного пакета обновится общее состояние; частичный пакет его не продвигает.</small></Surface>}
        {step === 'apply' && importPreview && <Status>{importPreview.entries.length ? 'Выбранные изменения готовы. При применении будет создана резервная копия и повторно проверены файлы.' : 'Результат уже достигнут. Запись файлов не требуется.'}</Status>}
        {step === 'done' && <EmptyState title={exported.length ? 'Пакет создан' : importPreview?.entries.length === 0 ? 'Новых изменений нет' : 'Изменения применены'}><Muted>{exported.length ? 'Передайте все части .md на внешний компьютер. После успешного применения пакета вернитесь сюда и подтвердите применение.' : importPreview?.entries.length === 0 ? 'Выбранный результат уже достигнут. Файлы не изменены; частичный перенос не продвигает общее состояние.' : 'Изменения записаны в локальные файлы. Проверьте результат и создайте коммит своими Git-инструментами. Отправку в Git выполните самостоятельно.'}</Muted>{exported.map(file => <p key={file}><code>{file}</code></p>)}<Button disabled={locked} onClick={openRepository}><Icon name="folder" />Открыть папку</Button></EmptyState>}
  </>;
}
